language: node_js
node_js:
  - 10

before_install:
  - npm install -g hexo-cli

install:
  - npm install
  - npm install hexo-deployer-git --save
  
script:
  - npm run clean && npm run build && npm run deploy 
  