language: node_js
node_js:
  - lts/*

before_install:
  - npm install -g hexo-cli

install:
  - npm install
  - npm install hexo-deployer-git --save
  
script:
  - hexo clean
  - hexo generate

after_script:
  - git config user.name "jackson"
  - git config user.email "codemak2r@163.com"
  - sed -i "s/access_token/${ACCESS_TOKEN}/g" ./_config.yml
  - hexo deploy